project_name: Export Demand Forecasting System
algorithm: CSA
dataset_path: C:\Users\NXTWAVE\Downloads\Export Demand Forecasting System\Table_B-4.csv
output_directory: C:\Users\NXTWAVE\Downloads\Export Demand Forecasting System
target_column: QV_Value
all_features:
- Year
- Percentage
- Market_Encoded
- Parameter_Encoded
- Lag_1
- Lag_2
- Rolling_Mean_3
selected_features:
- Rolling_Mean_3
model: RandomForestRegressor
csa_parameters:
  population_size: 20
  generations: 30
  awareness_probability: 0.2
  flight_length: 2
